### ISSUE TITLE
ServerDisconnectedError: Server disconnected

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#365] opened 2021-04-12 13:57 UTC
During the batch execution, the `ServerDisconnectedError` error occurred (while some jobs were running), which caused the bake to terminate and break.

IDK which context would be handy for this problem debugging, but there's some info:
- `synthesis-aws` cluster
- `job-89d61d6c-68e1-4f52-b3e8-fae809332fda` - batch executor job
- neither of the underlying jobs failed
- neuro-flow package version: `21.4.5`

<details><summary>Traceback</summary>
The error report looks awesome 😮

```yaml
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/.local/lib/python3.7/site-packages/neuro_flow/batch_executor.py:549 in run                 │
│                                                                                                  │
│   546 │   async def run(self) -> TaskStatus:                                                     │
│   547 │   │   with self._progress:                                                               │
│   548 │   │   │   try:                                                                           │
│ ❱ 549 │   │   │   │   result = await self._run()                                                 │
│   550 │   │   │   except (KeyboardInterrupt, asyncio.CancelledError):                            │
│   551 │   │   │   │   await self._cancel_unfinished()                                            │
│   552 │   │   │   │   result = TaskStatus.CANCELLED                                              │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_flow/batch_executor.py:605 in _run                │
│                                                                                                  │
│   602 │   │   │                                                                                  │
│   603 │   │   │   # Check for cancellation                                                       │
│   604 │   │   │   if not self._is_cancelling:                                                    │
│ ❱ 605 │   │   │   │   await self._refresh_attempt()                                              │
│   606 │   │   │   │                                                                              │
│   607 │   │   │   │   if not ok or self._attempt.result == TaskStatus.CANCELLED:                 │
│   608 │   │   │   │   │   await self._cancel_unfinished()                                        │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_flow/batch_executor.py:366 in _refresh_attempt    │
│                                                                                                  │
│   363 │                                                                                          │
│   364 │   async def _refresh_attempt(self) -> None:                                              │
│   365 │   │   self._attempt = await self._storage.find_attempt(                                  │
│ ❱ 366 │   │   │   self._attempt.bake, self._attempt.number                                       │
│   367 │   │   )                                                                                  │
│   368 │                                                                                          │
│   369 │   def _only_completed_needs(                                                             │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_flow/storage.py:677 in find_attempt               │
│                                                                                                  │
│    674 │   │   │   fname = f"{attempt_no:02d}.attempt"                                           │
│    675 │   │   │   pre = "0".zfill(DIGITS)                                                       │
│    676 │   │   │   init_name = f"{pre}.init.json"                                                │
│ ❱  677 │   │   │   init_data = await self._read_json(bake_uri / fname / init_name)               │
│    678 │   │   │   pre = "9" * DIGITS                                                            │
│    679 │   │   │   result_name = f"{pre}.result.json"                                            │
│    680 │   │   │   try:                                                                          │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_flow/storage.py:879 in _read_json                 │
│                                                                                                  │
│    876 │   │   return b"".join(ret).decode("utf-8")                                              │
│    877 │                                                                                         │
│    878 │   async def _read_json(self, url: URL) -> Any:                                          │
│ ❱  879 │   │   data = await self._read_file(url)                                                 │
│    880 │   │   return json.loads(data)                                                           │
│    881 │                                                                                         │
│    882 │   async def _write_file(                                                                │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_flow/storage.py:874 in _read_file                 │
│                                                                                                  │
│    871 │                                                                                         │
│    872 │   async def _read_file(self, url: URL) -> str:                                          │
│    873 │   │   ret = []                                                                          │
│ ❱  874 │   │   async for chunk in self._fs.open(url):                                            │
│    875 │   │   │   ret.append(chunk)                                                             │
│    876 │   │   return b"".join(ret).decode("utf-8")                                              │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_sdk/storage.py:343 in open                        │
│                                                                                                  │
│   340 │   │   │   raise ValueError("size should be >= 0")                                        │
│   341 │   │                                                                                      │
│   342 │   │   async with self._core.request(                                                     │
│ ❱ 343 │   │   │   "GET", url, timeout=timeout, auth=auth, headers=headers                        │
│   344 │   │   ) as resp:                                                                         │
│   345 │   │   │   if partial:                                                                    │
│   346 │   │   │   │   if resp.status != aiohttp.web.HTTPPartialContent.status_code:              │
│                                                                                                  │
│ /usr/local/lib/python3.7/contextlib.py:170 in __aenter__                                         │
│                                                                                                  │
│   167 │                                                                                          │
│   168 │   async def __aenter__(self):                                                            │
│   169 │   │   try:                                                                               │
│ ❱ 170 │   │   │   return await self.gen.__anext__()                                              │
│   171 │   │   except StopAsyncIteration:                                                         │
│   172 │   │   │   raise RuntimeError("generator didn't yield") from None                         │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/neuro_sdk/core.py:148 in request                        │
│                                                                                                  │
│   145 │   │   │   timeout=timeout,                                                               │
│   146 │   │   │   trace_request_ctx=trace_request_ctx,                                           │
│   147 │   │   │   # Use 4mb buffer as sometimes single job response can be huge.                 │
│ ❱ 148 │   │   │   read_bufsize=2 ** 22,                                                          │
│   149 │   │   ) as resp:                                                                         │
│   150 │   │   │   if 400 <= resp.status:                                                         │
│   151 │   │   │   │   err_text = await resp.text()                                               │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/aiohttp/client.py:1117 in __aenter__                    │
│                                                                                                  │
│   1114 │   │   return self.__await__()                                                           │
│   1115 │                                                                                         │
│   1116 │   async def __aenter__(self) -> _RetType:                                               │
│ ❱ 1117 │   │   self._resp = await self._coro                                                     │
│   1118 │   │   return self._resp                                                                 │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/aiohttp/client.py:544 in _request                       │
│                                                                                                  │
│    541 │   │   │   │   │   │   try:                                                              │
│    542 │   │   │   │   │   │   │   resp = await req.send(conn)                                   │
│    543 │   │   │   │   │   │   │   try:                                                          │
│ ❱  544 │   │   │   │   │   │   │   │   await resp.start(conn)                                    │
│    545 │   │   │   │   │   │   │   except BaseException:                                         │
│    546 │   │   │   │   │   │   │   │   resp.close()                                              │
│    547 │   │   │   │   │   │   │   │   raise                                                     │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py:890 in start                   │
│                                                                                                  │
│    887 │   │   │   while True:                                                                   │
│    888 │   │   │   │   # read response                                                           │
│    889 │   │   │   │   try:                                                                      │
│ ❱  890 │   │   │   │   │   message, payload = await self._protocol.read()  # type: ignore        │
│    891 │   │   │   │   except http.HttpProcessingError as exc:                                   │
│    892 │   │   │   │   │   raise ClientResponseError(                                            │
│    893 │   │   │   │   │   │   self.request_info,                                                │
│                                                                                                  │
│ /root/.local/lib/python3.7/site-packages/aiohttp/streams.py:604 in read                          │
│                                                                                                  │
│   601 │   │   │   assert not self._waiter                                                        │
│   602 │   │   │   self._waiter = self._loop.create_future()                                      │
│   603 │   │   │   try:                                                                           │
│ ❱ 604 │   │   │   │   await self._waiter                                                         │
│   605 │   │   │   except (asyncio.CancelledError, asyncio.TimeoutError):                         │
│   606 │   │   │   │   self._waiter = None                                                        │
│   607 │   │   │   │   raise                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ServerDisconnectedError: Server disconnected
[13:34:12] ERROR: Some unknown error happened. Please report an issue to https://github.com/neuro-inc/neuro-flow/issues/new with traceback printed above.
```
</details>

This problem occurs pretty often, especially while you attached to the executor (this doesn't break the batch, just really annoys).
Pls, ping me if any additional context is needed.

**Comment by romasku** [comment] 2021-06-04 10:53
This is caused by a random network error, and we cannot mitigate it completely.
To at least partially fix this, we will add a retry to all "read" requests we do. We cannot "retry" write requests as it can lead to bad behaviour (like job started two times, incontinent values in DB).
We will also add some notice about `neuro-flow restart` to the error message as it allows to continue bake from the point it failed.

**Comment by romasku** [comment] 2022-01-26 10:57
Since June we've added retry to "read" requests, and also we print info about `neuro-flow restart` if an error occurs. So I close this issue - if it starts to really annoy us one more time, we can re-open it.

**Closed by romasku** 2022-01-26 10:57 UTC
Labels: bug
